#!/bin/bash

# Restore environment variables from backups
export FORTRANFLAGSFLAGS="${COMPILERS_BACKUP_FORTRANFLAGS}"
export FFLAGS="${COMPILERS_BACKUP_FFLAGS}"
export LDFLAGS="${COMPILERS_BACKUP_LDFLAGS}"

# Clear backups
unset COMPILERS_BACKUP_FORTRANFLAGS
unset COMPILERS_BACKUP_FFLAGS
unset COMPILERS_BACKUP_LDFLAGS
